apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: the-stateful-set
spec:
  serviceName: "bozo"
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: the-pod
      labels:
        app: demo
    spec:
      containers:
      - name: old-container
        image: container:v1